baseURL = "https://jesse.works/"
languageCode = "en-us"
title = "Jesse Works"
summary = "Trust the process"
theme = "workout"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  contentTypes = ["posts"]